# Generated by Django 6.1 on 2026-08-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_folder_alter_note_options_note_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
