# Generated by Django 6.1 on 2026-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_note_folder_delete_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
